"Asar/asar.exe" "nmi fix/NMIFix.asm" "../base.smc"
"Asar/asar.exe" "separate status bar palettes and move layer 3 to subscreen fix/separate_status_bar_palettes_lm_fix.asm" "../base.smc"
"Asar/asar.exe" "Dynamic Z V3.5/Patch/DynamicZ.asm" "../base.smc"
"Asar/asar.exe" "luigi gfx/luigi.asm" "../base.smc"
"Asar/asar.exe" "SRAM_BWRAM_plus v1.3/MarioE's sram_plus/sram_plus.asm" "../base.smc"
"Asar/asar.exe" "overworld file load tweaks/overworld_file_load_tweaks.asm" "../base.smc"
"Asar/asar.exe" "background shake/background_shake.asm" "../base.smc"
"Asar/asar.exe" "better powerdown/better_powerdown.asm" "../base.smc"
"Asar/asar.exe" "coin cap/coin_cap.asm" "../base.smc"
"Asar/asar.exe" "coin tweaks/coin_tweaks.asm" "../base.smc"
"Asar/asar.exe" "credits save/creditsave.asm" "../base.smc"
"Asar/asar.exe" "custom sprite clippings/custsprclip.asm" "../base.smc"
"Asar/asar.exe" "entrance edit/EntranceEdit.asm" "../base.smc"
"Asar/asar.exe" "extended no more sprite tile limits/extendnstl.asm" "../base.smc"
"Asar/asar.exe" "flight spin fix/FlightSpinFix.asm" "../base.smc"
"Asar/asar.exe" "hex edits/paranormalyoshi'shousehexedits.asm" "../base.smc"
"Asar/asar.exe" "inline layer 3 messages/InlineLayer3Message.asm" "../base.smc"
"Asar/asar.exe" "item box mushroom priority fix/fixmush.asm" "../base.smc"
"Asar/asar.exe" "level constrain/LevelExtend.asm" "../base.smc"
"Asar/asar.exe" "level specific tile remapping/level_specific_tile_remapping.asm" "../base.smc"
"Asar/asar.exe" "luigi yoshi thank you message/luigi_yoshi_thank_you_message.asm" "../base.smc"
"Asar/asar.exe" "message box choice/Message_Box_Choice.asm" "../base.smc"
"Asar/asar.exe" "multiple midway points/multi_midway_1.7.asm" "../base.smc"
"Asar/asar.exe" "NoMoreSpriteTileLimits_v1.2.1/asarspritetiles.asm" "../base.smc"
"Asar/asar.exe" "objectool/objectool.asm" "../base.smc"
"Asar/asar.exe" "overworld save prompt/savepromptselect.asm" "../base.smc"
"Asar/asar.exe" "player tilemap editing patches/tilemaps/playertilemap_small.asm" "../base.smc"
"Asar/asar.exe" "player tilemap editing patches/tilemaps/playertilemap_super_fire.asm" "../base.smc"
"Asar/asar.exe" "player tilemap editing patches/tilemaps/playertilemap_cape.asm" "../base.smc"
"Asar/asar.exe" "player tilemap editing patches/tilemaps/playertilemap_special.asm" "../base.smc"
"Asar/asar.exe" "quickrom/quickrom.asm" "../base.smc"
"Asar/asar.exe" "rollover fix/RolloverFix.asm" "../base.smc"
"Asar/asar.exe" "score+9/score9.asm" "../base.smc"
"Asar/asar.exe" "separate mario palettes/separate_mario_palettes.asm" "../base.smc"
"Asar/asar.exe" "sepluigi_23_sa1/luigi_dynamic_z_compatible.asm" "../base.smc"
"Asar/asar.exe" "slope pass fix/slopepassfix.asm" "../base.smc"
"Asar/asar.exe" "smoke_position_v1.3/smoke_position.asm" "../base.smc"
"Asar/asar.exe" "time up fix/timeupfix.asm" "../base.smc"
"Asar/asar.exe" "title window cleaner/windex.asm" "../base.smc"
"Asar/asar.exe" "vertical level priority fix/VerticalLevelPriorityFix.asm" "../base.smc"
pause